### ISSUE TITLE
Doesn't build with lens-3.7

### ISSUE THREAD

**Issue by ocharles** [tanakh/aeson-lens#8]
```
Building aeson-lens-0.4.1.1...
Preprocessing library aeson-lens-0.4.1.1...
[1 of 1] Compiling Data.Aeson.Lens  ( Data/Aeson/Lens.hs, dist/build/Data/Aeson/Lens.o )

Data/Aeson/Lens.hs:45:13:
    Not in scope: `index'
    Perhaps you meant one of these:
      `T.index' (imported from Data.Text),
      `V.indexM' (imported from Data.Vector)

Data/Aeson/Lens.hs:157:18:
    Not in scope: `index'
    Perhaps you meant one of these:
      `T.index' (imported from Data.Text),
      `V.indexM' (imported from Data.Vector)

Data/Aeson/Lens.hs:176:19:
    Not in scope: `index'
    Perhaps you meant one of these:
      `T.index' (imported from Data.Text),
      `V.indexM' (imported from Data.Vector)

Data/Aeson/Lens.hs:186:21:
    Not in scope: `index'
    Perhaps you meant one of these:
      `T.index' (imported from Data.Text),
      `V.indexM' (imported from Data.Vector)
```

**Comment by tanakh** [comment]
Thank you for report and patch!
I merged and released it.
